/**
 * The hash printed on a legal page, and stamped into every acceptance row, is a claim that the text
 * a customer read is the text they agreed to. Nothing else in the system checks that claim — the
 * hash is generated by a script someone has to remember to run, and a document edited without
 * re-running it would publish a stale hash while looking completely correct.
 *
 * These tests recompute the hashes FROM THE MARKDOWN, on purpose, rather than importing anything
 * from scripts/hash-legal.mjs. A test that verifies a generator by calling the generator only
 * proves the generator is deterministic. The five lines of normalise-and-hash below are duplicated
 * deliberately, and that duplication is the test.
 */

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const { LEGAL_META } = require('./generated/legalMeta')
const { LEGAL_TEXT } = require('./generated/legalText')
const { DOC_TYPES, legalDoc, isDraft, missingLegalValues, acceptancePayload } = require('./index')

function readCanonical(filename) {
  const raw = fs.readFileSync(path.join(__dirname, filename), 'utf8')
  return raw.replace(/^﻿/, '').replace(/\r\n/g, '\n')
}

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex')
}

describe('legal document hashes', () => {
  it.each(DOC_TYPES)('%s: committed hash matches the markdown on disk', (docType) => {
    const meta = LEGAL_META[docType]
    expect(meta).toBeDefined()
    const canonical = readCanonical(meta.filename)
    expect(sha256(canonical)).toBe(meta.sha256)
  })

  it.each(DOC_TYPES)('%s: bundled text is byte-identical to the markdown', (docType) => {
    const canonical = readCanonical(LEGAL_META[docType].filename)
    expect(LEGAL_TEXT[docType]).toBe(canonical)
  })

  it.each(DOC_TYPES)('%s: byte count is recorded correctly', (docType) => {
    const canonical = readCanonical(LEGAL_META[docType].filename)
    expect(Buffer.byteLength(canonical, 'utf8')).toBe(LEGAL_META[docType].bytes)
  })

  // The hash is only verifiable by a third party if it is over LF bytes. A file that had picked up
  // CRLF would still hash consistently here (the normaliser runs on both sides) but would no longer
  // match what a customer gets from `sha256sum` on the file they downloaded from git.
  it.each(DOC_TYPES)('%s: markdown on disk contains no CRLF', (docType) => {
    const raw = fs.readFileSync(path.join(__dirname, LEGAL_META[docType].filename), 'utf8')
    expect(raw).not.toMatch(/\r\n/)
  })
})

describe('registry and generated metadata agree', () => {
  it('every registered document has generated metadata, and vice versa', () => {
    expect(Object.keys(LEGAL_META).sort()).toEqual([...DOC_TYPES].sort())
    expect(Object.keys(LEGAL_TEXT).sort()).toEqual([...DOC_TYPES].sort())
  })

  it.each(DOC_TYPES)('%s: legalDoc() exposes a non-empty hash and version', (docType) => {
    const doc = legalDoc(docType)
    expect(doc.sha256).toMatch(/^[0-9a-f]{64}$/)
    expect(doc.version).toMatch(/^\d+\.\d+$/)
    expect(doc.effectiveAd).toMatch(/^\d{4}-\d{2}-\d{2}$/)
    expect(doc.effectiveBs).toMatch(/^\d{4}-\d{2}-\d{2}$/)
  })
})

describe('draft detection', () => {
  // Not an assertion that the documents ARE complete — they are not yet, and this test must not
  // start failing merely because someone filled the company registration number in. It asserts the
  // detector works, which is what stops a page with a raw placeholder being presented as in force.
  it('reports a document with an unfilled placeholder as a draft', () => {
    const drafts = DOC_TYPES.filter(isDraft)
    const withMarkers = DOC_TYPES.filter(
      (t) => (LEGAL_META[t].missing || []).length > 0
    )
    expect(drafts.sort()).toEqual(withMarkers.sort())
  })

  it('missingLegalValues() is the union across documents, deduplicated and sorted', () => {
    const expected = [
      ...new Set(DOC_TYPES.flatMap((t) => LEGAL_META[t].missing || [])),
    ].sort()
    expect(missingLegalValues()).toEqual(expected)
  })

  it('no document still contains a placeholder marker the detector did not report', () => {
    for (const docType of DOC_TYPES) {
      const found = [
        ...new Set(
          [...LEGAL_TEXT[docType].matchAll(/\[\[NEEDS VALUE: ([A-Z0-9_]+)\]\]/g)].map((m) => m[1])
        ),
      ].sort()
      expect(found).toEqual([...(LEGAL_META[docType].missing || [])].sort())
    }
  })
})

describe('acceptancePayload', () => {
  it('carries a version and hash for every document and nothing else', () => {
    const payload = acceptancePayload()
    expect(Object.keys(payload).sort()).toEqual([...DOC_TYPES].sort())
    for (const docType of DOC_TYPES) {
      expect(Object.keys(payload[docType]).sort()).toEqual(['sha256', 'version'])
      expect(payload[docType].sha256).toBe(LEGAL_META[docType].sha256)
    }
  })

  // The server reads identity and address off the request. A payload that offered them would be
  // inviting the browser to attribute its own acceptance, which is the defect this whole design
  // exists to avoid — so assert they are absent rather than trusting the shape stays as written.
  it('never carries identity or address fields', () => {
    const serialised = JSON.stringify(acceptancePayload())
    for (const forbidden of ['ip', 'user_id', 'userId', 'client_id', 'clientId', 'user_agent']) {
      expect(serialised).not.toContain(forbidden)
    }
  })
})
