// Turns the canonical legal markdown in src/legal/*.md into two generated modules:
//
//   src/legal/generated/legalMeta.js  — hash, byte length and unfilled-placeholder list per doc.
//                                       Tiny, and safe to import from anywhere (Login imports it
//                                       to stamp the acceptance it sends to the server).
//   src/legal/generated/legalText.js  — the documents themselves. Several tens of kB of prose, so
//                                       nothing may import it statically; it is reached only
//                                       through the dynamic import in src/legal/index.js.
//
// Run it after editing any legal document:  node scripts/hash-legal.mjs
// src/legal/legalHash.test.js fails if you forget.
//
// Why the hash is computed here and not by a Postgres trigger, which is what the spec asked for:
// pgcrypto's digest() lives in the `extensions` schema on Supabase, and every SECURITY DEFINER
// function in this project sets `search_path TO 'public'`, so an unqualified call fails at runtime
// rather than at deploy time. This project already made that call once, deliberately, and wrote
// down why (20260812110000_pin_vault.sql lines 51-56). Node's crypto is the equivalent of the
// WebCrypto route the Edge Functions take for the same reason.
//
// LINE ENDINGS ARE NORMALISED TO LF BEFORE HASHING, and this is load-bearing. The hash is a
// promise to the reader that the text they can see is the text that was agreed; if it changed
// depending on whether the file was checked out on Windows or Linux, it would promise nothing.
// .gitattributes already keeps this repo LF, so normalising is belt-and-braces — but the belt is
// the part a reader can verify independently, with `sha256sum` on a file they downloaded.

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const LEGAL_DIR = join(ROOT, 'src', 'legal')
const OUT_DIR = join(LEGAL_DIR, 'generated')

// docType -> filename. Keep in step with DOCUMENTS in src/legal/index.js; the test asserts they
// agree, because a document present in one and not the other is a page that renders nothing or a
// hash nobody checks.
export const SOURCES = {
  terms: 'terms-v1.0.md',
  privacy: 'privacy-v1.0.md',
}

// A marker left in the prose where a value is genuinely not known yet — a company registration
// number that has not been issued, an address nobody has typed. Part E rule 5 of the spec that
// prompted this work puts it plainly: a Terms page that shows an unfilled placeholder in public is
// worse than no Terms page. So the marker is machine-detectable, and everything downstream treats a
// document that still has one as a DRAFT: index.js reports it, the page shows a banner, and the
// build refuses to call it published.
const PLACEHOLDER_RE = /\[\[NEEDS VALUE: ([A-Z0-9_]+)\]\]/g

export function normalise(text) {
  // Strip a UTF-8 BOM as well as CRLF: an editor that adds one would otherwise silently change the
  // hash of a document whose visible text is identical.
  return text.replace(/^﻿/, '').replace(/\r\n/g, '\n')
}

export function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

export function missingValues(text) {
  return [...new Set([...text.matchAll(PLACEHOLDER_RE)].map((m) => m[1]))].sort()
}

export function readDocs() {
  const out = {}
  for (const [docType, filename] of Object.entries(SOURCES)) {
    const text = normalise(readFileSync(join(LEGAL_DIR, filename), 'utf8'))
    out[docType] = {
      filename,
      text,
      sha256: sha256(text),
      bytes: Buffer.byteLength(text, 'utf8'),
      missing: missingValues(text),
    }
  }
  return out
}

const BANNER = `// GENERATED by scripts/hash-legal.mjs — do not edit by hand.\n// Edit src/legal/*.md and re-run: node scripts/hash-legal.mjs\n`

function main() {
  const docs = readDocs()
  mkdirSync(OUT_DIR, { recursive: true })

  const meta = Object.fromEntries(
    Object.entries(docs).map(([k, d]) => [
      k,
      { filename: d.filename, sha256: d.sha256, bytes: d.bytes, missing: d.missing },
    ])
  )
  writeFileSync(
    join(OUT_DIR, 'legalMeta.js'),
    `${BANNER}\nexport const LEGAL_META = ${JSON.stringify(meta, null, 2)}\n`,
    'utf8'
  )

  // JSON.stringify rather than a template literal: the prose contains backticks in code spans and
  // could one day contain ${, both of which a template literal would either break on or silently
  // interpolate. A JSON string literal is a valid JS string literal and cannot do either.
  const textEntries = Object.entries(docs)
    .map(([k, d]) => `  ${JSON.stringify(k)}: ${JSON.stringify(d.text)},`)
    .join('\n')
  writeFileSync(
    join(OUT_DIR, 'legalText.js'),
    `${BANNER}\nexport const LEGAL_TEXT = {\n${textEntries}\n}\n`,
    'utf8'
  )

  for (const [k, d] of Object.entries(docs)) {
    const flag = d.missing.length ? `DRAFT — missing ${d.missing.join(', ')}` : 'complete'
    console.log(`${k.padEnd(10)} ${d.sha256}  ${String(d.bytes).padStart(6)} bytes  ${flag}`)
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
