-- Automatic deletion of a lapsed trial's data, because the Terms promise it and nothing did it.
--
-- Terms 4.3 and 7.6, and Privacy Policy 9, say a trial account's Customer Data is deleted 15 days
-- after the trial ends. `clients.trial_purge_at` has been written at every signup since the form
-- was built (register_trial sets it to +22 days) and NOTHING has ever read it. A published
-- retention commitment with no mechanism behind it is not a bug in the ordinary sense -- it is a
-- statement to customers and to a regulator that is not true.
--
-- ── THE DANGER, STATED PLAINLY ───────────────────────────────────────────────────────────────
-- This runs unattended and deletes live tenant data. The realistic way it destroys a PAYING
-- customer is not a coding error: `is_trial` is cleared by exactly one thing, the "Convert to paid"
-- button in Admin -> Clients (AdminClients.js convertTrialToPaid). An admin who takes payment,
-- sets the module dates in the drawer, and never presses that button leaves a real customer sitting
-- at is_trial = true with a trial_purge_at long past.
--
-- So the flag is not treated as evidence. SIX independent guards must ALL hold, and any one of
-- them is enough on its own to save a real customer:
--
--   1. is_trial is still true                      -- never converted
--   2. trial_purge_at exists and has passed        -- the promised date has actually arrived
--   3. NO module has a paid window open            -- ims/hr/pos/suite/subscription_ends_at are all
--                                                     null or past. This is the guard that catches
--                                                     the forgotten button: converting sets dates.
--   4. subscribe_requested is false                -- someone asking to pay is not abandoned
--   5. nobody has signed in since the trial expired -- profiles.last_seen_at. A tenant still using
--                                                     the product every day is not a dead trial,
--                                                     whatever its flags say.
--   6. a backup exists, taken after the trial expired -- clients.last_backup_at. This one is not
--                                                     mine: `.claude/rules/data-export.md` already
--                                                     said last_backup_at "is the gate any future
--                                                     purge must check", and the whole pre-purge
--                                                     backup mechanism (useAutoPurgeBackup, T-72h)
--                                                     was built as the parachute for exactly this
--                                                     jump. Deleting data the parachute never
--                                                     caught would waste the feature that exists
--                                                     to make this survivable.
--
-- The guards live HERE, in a readable SQL function, rather than in the Edge Function that executes
-- them, so the decision can be audited and dry-run from the SQL editor without reading Deno.
--
-- ── WHAT IT DELETES, AND WHAT SURVIVES ───────────────────────────────────────────────────────
-- Customer Data, via the same deleteClientDataFor() sequence the admin Danger Zone uses -- ONE
-- implementation, extracted for this (S672). A second hand-ordered copy of ~130 FK-sensitive
-- deletes would drift the first time a table was added to one and not the other, and the symptom
-- would be a row that quietly survives a wipe.
--
-- The `clients` row SURVIVES, deactivated and stamped with trial_purged_at. Deleting it would take
-- legal_acceptances.client_id with it (ON DELETE SET NULL) and erase which business a consent
-- record belonged to -- and that record is retained for 7 years by the very policy this job exists
-- to honour. The Terms say Customer Data is deleted; they do not say the account shell is.
--
-- Requires the pg_cron and pg_net extensions. Both are available on Supabase but may need enabling
-- in Dashboard -> Database -> Extensions first; the CREATE EXTENSION statements below are
-- idempotent and will do it where permitted.

-- ── A secret for the scheduler to authenticate with ──────────────────────────────────────────
-- Generated by Postgres, exactly like pin_pepper (20260812110000) and for the same reason: there is
-- no step for a human to skip or fat-finger, and nothing to copy into a password manager. An env
-- var would have to be set by hand on a function that is otherwise self-configuring.
ALTER TABLE public.app_secrets
  ADD COLUMN IF NOT EXISTS purge_secret text NOT NULL
  DEFAULT replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');

COMMENT ON COLUMN public.app_secrets.purge_secret IS
  'Shared secret the pg_cron trial-purge job presents to admin-user-ops as x-purge-secret. Rotating it means updating the cron command in the same transaction.';

-- ── The stamp, so a purged shell is distinguishable from a merely inactive one ───────────────
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS trial_purged_at timestamptz;

COMMENT ON COLUMN public.clients.trial_purged_at IS
  'When this trial account had its Customer Data deleted under the retention policy. The clients row is kept so legal_acceptances retains its link; everything else is gone.';

-- ── The log. An unattended deleter that leaves no trace is not operable ──────────────────────
CREATE TABLE IF NOT EXISTS public.trial_purge_log (
  id          bigserial PRIMARY KEY,
  client_id   uuid,                 -- no FK: the row must outlive the client if one is ever removed
  client_name text,
  outcome     text NOT NULL CHECK (outcome IN ('purged','failed','skipped')),
  detail      text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS trial_purge_log_created_idx ON public.trial_purge_log (created_at DESC);

ALTER TABLE public.trial_purge_log ENABLE ROW LEVEL SECURITY;

-- Admin-only, read-only. This names clients and what was destroyed; it is operator forensics, not
-- tenant data. No write policy at all -- the service role inside the Edge Function writes it.
DROP POLICY IF EXISTS trial_purge_log_select ON public.trial_purge_log;
CREATE POLICY trial_purge_log_select ON public.trial_purge_log
  FOR SELECT TO authenticated
  USING (COALESCE((SELECT public.is_admin()), false));

GRANT SELECT ON public.trial_purge_log TO authenticated;
GRANT ALL    ON public.trial_purge_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.trial_purge_log_id_seq TO service_role;

-- ── The decision ─────────────────────────────────────────────────────────────────────────────
-- Read this on its own to know exactly what the job would destroy tonight:
--     SELECT * FROM public.trials_due_for_purge();
DROP FUNCTION IF EXISTS public.trials_due_for_purge();
CREATE FUNCTION public.trials_due_for_purge()
  RETURNS TABLE (
    client_id      uuid,
    client_name    text,
    trial_purge_at timestamptz,
    last_seen_at   timestamptz,
    last_backup_at timestamptz,
    blocked_reason text
  )
  LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'public'
  AS $fn$
  -- Returns every trial whose promised deletion date has PASSED, with blocked_reason saying why it
  -- is being held back -- NULL means purge it. Deliberately not a filtered list of the safe ones:
  -- an operator has to be able to see "three trials are overdue and none has a backup", which a
  -- query that silently omitted them could never show. The executor purges only NULL rows.
  SELECT
    c.id,
    c.name,
    c.trial_purge_at,
    s.last_seen,
    c.last_backup_at,
    CASE
      -- guard 3: any paid window open. The guard that catches the forgotten "Convert to paid"
      -- button, which is the realistic way this job could ever reach a real customer.
      WHEN GREATEST(
             COALESCE(c.ims_ends_at,          '-infinity'::timestamptz),
             COALESCE(c.hr_ends_at,           '-infinity'::timestamptz),
             COALESCE(c.pos_ends_at,          '-infinity'::timestamptz),
             COALESCE(c.suite_ends_at,        '-infinity'::timestamptz),
             COALESCE(c.subscription_ends_at, '-infinity'::timestamptz)
           ) >= now()
        THEN 'a paid module window is still open'
      -- guard 4
      WHEN COALESCE(c.subscribe_requested, false)
        THEN 'client has asked to subscribe'
      -- guard 5
      WHEN COALESCE(s.last_seen, '-infinity'::timestamptz)
           >= COALESCE(c.trial_expires_at, c.trial_purge_at)
        THEN 'someone signed in after the trial expired'
      -- guard 6
      WHEN c.last_backup_at IS NULL
        THEN 'no backup has ever been taken'
      WHEN c.last_backup_at < COALESCE(c.trial_expires_at, c.trial_purge_at)
        THEN 'the only backup predates the end of the trial'
      ELSE NULL
    END
  FROM clients c
  LEFT JOIN LATERAL (
    SELECT max(p.last_seen_at) AS last_seen FROM profiles p WHERE p.client_id = c.id
  ) s ON true
  WHERE c.is_trial IS TRUE                    -- guard 1
    AND c.trial_purge_at IS NOT NULL
    AND c.trial_purge_at < now()              -- guard 2
    AND c.trial_purged_at IS NULL             -- not already done
$fn$;

REVOKE EXECUTE ON FUNCTION public.trials_due_for_purge() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.trials_due_for_purge() TO service_role;

COMMENT ON FUNCTION public.trials_due_for_purge() IS
  'Trials whose promised deletion date has passed. blocked_reason NULL means purge; anything else is why it is being held. All six safety guards live here, so the decision is auditable in SQL; the Edge Function only executes rows this marks NULL.';

-- ── The schedule ─────────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

-- 19:20 UTC = 01:05 Nepal (+05:45), deliberately outside service hours: if this job ever misbehaves
-- it should do so when no till is open and an operator is not mid-shift.
--
-- Unscheduled first so re-running this migration replaces rather than duplicates the job.
SELECT cron.unschedule('crest-purge-expired-trials')
  WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'crest-purge-expired-trials');

SELECT cron.schedule(
  'crest-purge-expired-trials',
  '20 19 * * *',
  $job$
  SELECT extensions.http_post(
    url     := current_setting('app.settings.functions_url', true) || '/admin-user-ops',
    headers := jsonb_build_object(
      'Content-Type',   'application/json',
      'Authorization',  'Bearer ' || current_setting('app.settings.anon_key', true),
      'x-purge-secret', (SELECT purge_secret FROM public.app_secrets WHERE id = 1)
    ),
    body    := jsonb_build_object('action', 'purge_due_trials', 'dry_run', false)
  );
  $job$
);

-- The two settings the job composes its request from. They are NOT secrets (the anon key ships in
-- every browser bundle; the functions URL is public), which is why they are database settings
-- rather than another app_secrets column -- and why the x-purge-secret above is the thing that
-- actually authenticates the call.
--
-- SET THESE BEFORE THE JOB FIRST RUNS, substituting the project ref. Until they are set, the job
-- posts to a null URL and fails harmlessly rather than deleting anything:
--
--   ALTER DATABASE postgres SET app.settings.functions_url = 'https://<ref>.supabase.co/functions/v1';
--   ALTER DATABASE postgres SET app.settings.anon_key      = '<the anon key>';

notify pgrst, 'reload schema';

-- Verification -------------------------------------------------------------------------------
-- 1. What would it destroy tonight? Run this FIRST, on the live database, and read every row.
--    Rows with blocked_reason IS NULL are the ones that WILL be deleted. Read those names aloud.
-- SELECT * FROM public.trials_due_for_purge() ORDER BY blocked_reason NULLS FIRST;
--
-- 1b. Overdue but held back, and why -- the list an operator has to act on, usually by opening
--     Admin -> Clients so the pre-purge backup runs.
-- SELECT client_name, trial_purge_at, blocked_reason FROM public.trials_due_for_purge()
--  WHERE blocked_reason IS NOT NULL;
--
-- 2. The job exists and is scheduled.
-- SELECT jobname, schedule, active FROM cron.job WHERE jobname = 'crest-purge-expired-trials';
--
-- 3. The settings resolve (both must be non-null, or the POST goes nowhere).
-- SELECT current_setting('app.settings.functions_url', true),
--        current_setting('app.settings.anon_key', true);
--
-- 4. End to end WITHOUT deleting: call the function with dry_run and read what it would do.
--    curl -s "$FUNCTIONS_URL/admin-user-ops" -H "Authorization: Bearer $ANON_KEY" \
--      -H "x-purge-secret: $(psql -tAc 'select purge_secret from app_secrets where id=1')" \
--      -H 'Content-Type: application/json' \
--      -d '{"action":"purge_due_trials","dry_run":true}'
--
-- 5. Afterwards, what it actually did.
-- SELECT * FROM public.trial_purge_log ORDER BY created_at DESC LIMIT 50;
--
-- 6. Grants: authenticated may read the log and may NOT execute the decision function.
-- SELECT has_table_privilege('authenticated','public.trial_purge_log','SELECT'),
--        has_function_privilege('authenticated','public.trials_due_for_purge()','EXECUTE');
--    Expect: t, f
